# Generated by Django 5.0 on 2026-04-25 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoIoT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=20, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('esp32', 'ESP32'), ('esp8266', 'ESP8266'), ('raspberry', 'Raspberry Pi'), ('otro', 'Otro')], default='esp32', max_length=20)),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=20)),
                ('ultimo_ping', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstacionMeteorologica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=250)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'Mantenimiento')], default='activa', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=7)),
                ('sensacion_termica', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alerta_activa', models.BooleanField(default=False)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('unidad', models.CharField(max_length=20)),
                ('rango_min', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rango_max', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(max_length=80)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('ocurrido_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComandoRemoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=100)),
                ('origen', models.CharField(choices=[('dashboard', 'Dashboard'), ('automatico', 'Automático'), ('api', 'API')], default='dashboard', max_length=20)),
                ('ejecutado', models.BooleanField(default=False)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dispositivoiot')),
            ],
        ),
        migrations.CreateModel(
            name='Actuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('relay', 'Relay'), ('ventilador', 'Ventilador'), ('nebulizador', 'Nebulizador'), ('led', 'LED'), ('otro', 'Otro')], default='relay', max_length=20)),
                ('activo', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dispositivoiot')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estacionmeteorologica'),
        ),
        migrations.CreateModel(
            name='EstadoActuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('encendido', 'Encendido'), ('apagado', 'Apagado'), ('error', 'Error')], max_length=20)),
                ('origen', models.CharField(blank=True, max_length=60, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.actuador')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRiesgoTermico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('moderado', 'Moderado'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('indice_calor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('evaluado_en', models.DateTimeField(auto_now_add=True)),
                ('lectura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lecturasensor')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('valor_detectado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('canal', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], default='telegram', max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='activa', max_length=20)),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
                ('lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lecturasensor')),
            ],
        ),
        migrations.CreateModel(
            name='LogConectividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('conexion', 'Conexión'), ('desconexion', 'Desconexión'), ('timeout', 'Timeout'), ('error', 'Error')], max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('ocurrido_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dispositivoiot')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=150)),
                ('canal', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.alerta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaComando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exito', models.BooleanField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('respondido_en', models.DateTimeField(auto_now_add=True)),
                ('comando', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.comandoremoto')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=80)),
                ('precision_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('falla', 'Falla')], default='activo', max_length=20)),
                ('calibrado_en', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dispositivoiot')),
                ('tipo_variable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.tipovariable')),
            ],
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sensor'),
        ),
        migrations.CreateModel(
            name='UmbralAlerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_max', models.DecimalField(decimal_places=2, max_digits=7)),
                ('severidad', models.CharField(choices=[('info', 'Info'), ('advertencia', 'Advertencia'), ('critico', 'Crítico')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tipovariable')),
            ],
        ),
        migrations.AddField(
            model_name='alerta',
            name='umbral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dashboard.umbralalerta'),
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80)),
                ('valor', models.TextField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estacionmeteorologica')),
            ],
            options={
                'unique_together': {('estacion', 'clave')},
            },
        ),
    ]
